version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: demo123
      POSTGRES_DB: inventorydb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - inventory-net

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:demo123@db:5432/inventorydb
    ports:
      - "5001:5000"
    depends_on:
      - db
    networks:
      - inventory-net

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - inventory-net

networks:
  inventory-net:
    driver: bridge
